// src/lib/data.ts

export const COMPANY = {
  name: 'Jaybhadra Builders',
  tagline: 'Building Dreams, Delivering Trust',
  location: 'Sangamner, Maharashtra, India',
  phone: '+91 9130711811',
  phoneRaw: '919130711811',
  email: 'info@jayabhadrabuilders.com',
  whatsapp: '919130711811',
  founded: '2010',
  address: 'Near Bus Stand, Sangamner, Ahmednagar District, Maharashtra - 422605',
  mapEmbed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d60456.06986738773!2d74.16831!3d19.57335!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bdc4a4b9fb77571%3A0xa4a4d9e15a4b14b3!2sSangamner%2C%20Maharashtra!5e0!3m2!1sen!2sin!4v1699876543210',
};

export const STATS = [
  { value: 27, label: 'Projects', suffix: '+' },
  { value: 14, label: 'Years Experience', suffix: '+' },
  { value: 500, label: 'Happy Families', suffix: '+' },
  { value: 100, label: 'Client Satisfaction', suffix: '%' },
];

export const PROJECTS = [
  {
    id: 1,
    name: 'Golden City',
    location: 'Sangamner, Maharashtra',
    category: 'residential',
    status: 'completed',
    specs: '2BHK, 3BHK',
    completionYear: '2022',
    units: '48 Units',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2024/10/1-3.png',
    description: 'Premium residential complex with modern amenities and elegant design in the heart of Sangamner.',
  },
  {
    id: 2,
    name: 'Professor Colony',
    location: 'Sangamner, Maharashtra',
    category: 'residential',
    status: 'completed',
    specs: 'Residential',
    completionYear: '2022',
    units: 'Residential Units',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2024/10/2-3.png',
    description: 'Well-planned residential colony built with premium quality materials and modern infrastructure.',
  },
  {
    id: 3,
    name: 'Golden City Phase II',
    location: 'Sangamner, Maharashtra',
    category: 'residential',
    status: 'completed',
    specs: '2BHK, 3BHK',
    completionYear: '2023',
    units: 'Residential Units',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2024/10/3-1.png',
    description: 'Second phase of the successful Golden City project with upgraded amenities and finishing.',
  },
  {
    id: 4,
    name: 'Shelu',
    location: 'Shelu, Maharashtra',
    category: 'residential',
    status: 'completed',
    specs: 'Residential',
    completionYear: '2023',
    units: 'Residential Units',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2024/10/4-1.png',
    description: 'Quality residential construction delivering comfortable and affordable homes at Shelu.',
  },
  {
    id: 5,
    name: 'Near Pachore Hospital',
    location: 'Sangamner, Maharashtra',
    category: 'residential',
    status: 'completed',
    specs: 'Residential',
    completionYear: '2023',
    units: 'Residential Units',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2024/10/5-1.png',
    description: 'Strategically located residential project near Pachore Hospital with easy access to all amenities.',
  },
  {
    id: 6,
    name: 'Golden City, Gunjalwadi',
    location: 'Gunjalwadi, Sangamner',
    category: 'residential',
    status: 'completed',
    specs: 'Residential',
    completionYear: '2023',
    units: 'Residential Units',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2024/10/7.png',
    description: 'Premium housing project at Gunjalwadi offering spacious homes with top-quality construction.',
  },
  {
    id: 7,
    name: 'Golden City, Sangamner',
    location: 'Sangamner, Maharashtra',
    category: 'residential',
    status: 'ongoing',
    specs: '2BHK, 3BHK, Shops',
    units: 'Wing A — 24 Units | Wing B & C — 42 Units | 12 Shops',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2025/04/1.png',
    description: 'Flagship ongoing project with Wing A, B & C residential towers and ground floor commercial shops.',
    urgency: 'Limited units available!',
  },
  {
    id: 8,
    name: 'Nirmal Nagar',
    location: 'Sangamner, Maharashtra',
    category: 'residential',
    status: 'ongoing',
    specs: 'Residential',
    units: 'Residential Units',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2025/04/2.png',
    description: 'Modern residential project at Nirmal Nagar, Sangamner — offering quality homes at great value.',
    urgency: 'Booking open now!',
  },
  {
    id: 9,
    name: 'Rahane Mala',
    location: 'Sangamner, Maharashtra',
    category: 'residential',
    status: 'ongoing',
    specs: 'Residential',
    units: 'Residential Units',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2025/04/4.png',
    description: 'Upcoming residential project at Rahane Mala with premium construction and modern design.',
    urgency: 'Pre-launch offer!',
  },
  {
    id: 10,
    name: 'Takeshwar Temple, Ranemala',
    location: 'Ranemala, Sangamner',
    category: 'residential',
    status: 'completed',
    specs: 'Residential',
    completionYear: '2024',
    units: 'Residential Units',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2025/04/3.png',
    description: 'Peaceful residential project near Takeshwar Temple at Ranemala with serene surroundings.',
  },
  {
    id: 11,
    name: 'Saishraddha Chowk',
    location: 'Sangamner, Maharashtra',
    category: 'commercial',
    status: 'completed',
    specs: 'Commercial Complex',
    completionYear: '2024',
    units: 'Commercial Units',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2025/04/6.png',
    description: 'Prime commercial complex at Saishraddha Chowk — the busiest junction in Sangamner city.',
  },
  {
    id: 12,
    name: 'Golden City Sangamner',
    location: 'Sangamner, Maharashtra',
    category: 'residential',
    status: 'ongoing',
    specs: '2BHK, 3BHK, Penthouse',
    units: 'Wing A — 24 Units | Wing B & C — 42 Units | 12 Shops',
    image: 'https://jaybhadrabuilders.com/wp-content/uploads/2025/04/5.png',
    description: 'Latest phase of Golden City with penthouse options and premium specifications throughout.',
    urgency: 'Only a few units left!',
  },
];

export const SERVICES = [
  {
    id: 1,
    title: 'Premium Bungalows',
    icon: '🏡',
    description: 'Standalone luxury bungalows with private gardens, parking, and premium finishes tailored to your lifestyle.',
  },
  {
    id: 2,
    title: 'Residential Houses',
    icon: '🏘️',
    description: 'Quality residential complexes with modern amenities, security, and community living designed for families.',
  },
  {
    id: 3,
    title: 'Commercial Buildings',
    icon: '🏢',
    description: 'Purpose-built commercial spaces including offices, business parks, and mixed-use developments.',
  },
  {
    id: 4,
    title: 'Shops & Showrooms',
    icon: '🏬',
    description: 'Prime retail spaces in high-footfall locations, designed for maximum business visibility and convenience.',
  },
  {
    id: 5,
    title: 'RCC Structures',
    icon: '🔩',
    description: 'Industrial-grade RCC construction using top-tier materials and proven engineering for lasting durability.',
  },
  {
    id: 6,
    title: 'Material Supply',
    icon: '🧱',
    description: 'Quality construction materials sourced directly — cement, steel, bricks, and fittings at competitive rates.',
  },
];

export const WHY_US = [
  {
    icon: '💎',
    title: 'Premium Materials',
    description: 'We use only ISI-certified, Grade A materials — from foundation to finishing — ensuring lasting quality.',
  },
  {
    icon: '👷',
    title: 'Expert Team',
    description: '14+ years of collective expertise. Our engineers, architects and craftsmen bring unmatched skill to every project.',
  },
  {
    icon: '⚙️',
    title: 'Modern Technology',
    description: 'Advanced construction techniques, 3D design previews, and smart home integration in select projects.',
  },
  {
    icon: '⏱️',
    title: 'On-Time Delivery',
    description: 'We respect your investment timeline. 95% of our projects are delivered on or before the committed date.',
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Rajesh Patil',
    location: 'Sangamner',
    property: '3BHK — Shivprasad Residency',
    rating: 5,
    review: 'Jaybhadra Builders delivered our dream home exactly on time. The quality of materials and finishing is outstanding. Their team was professional and transparent throughout the process. Highly recommend!',
  },
  {
    id: 2,
    name: 'Priya & Sunil Sharma',
    location: 'Sangamner',
    property: 'Bungalow — Green Valley',
    rating: 5,
    review: 'We were apprehensive about investing in real estate, but Jaybhadra Builders made the entire journey smooth and trust-worthy. Our bungalow exceeded all expectations. Truly building dreams!',
  },
  {
    id: 3,
    name: 'Mahesh Deshmukh',
    location: 'Ahmednagar',
    property: 'Shop — Swami Vivekanand Hub',
    rating: 5,
    review: 'Got a shop for my business in their commercial complex. Prime location, perfect construction quality. The 3-year maintenance guarantee gives great peace of mind. Will invest again!',
  },
  {
    id: 4,
    name: 'Anita Kulkarni',
    location: 'Sangamner',
    property: '2BHK — Samarth Nagar',
    rating: 5,
    review: 'As a first-time homebuyer, I was nervous about the process. The Jaybhadra team guided me at every step. Transparent pricing, no hidden costs. My family is very happy!',
  },
  {
    id: 5,
    name: 'Vinod Waghmare',
    location: 'Sangamner',
    property: 'Office Space — Mahadev Business Park',
    rating: 5,
    review: 'Premium office space with modern infrastructure at a competitive price. The building quality is top-notch and the management is very responsive. Highly satisfied with my investment.',
  },
];

export const TRUST_BADGES = [
  '✅ Trusted Since 2010',
  '🔧 3-Year Maintenance Guarantee',
  '📋 RERA Compliant Projects',
  '🏅 ISO Certified Construction',
  '🤝 500+ Happy Families',
  '⭐ 4.9/5 Customer Rating',
];

export const BUDGET_OPTIONS = [
  'Under ₹20 Lakhs',
  '₹20 – ₹40 Lakhs',
  '₹40 – ₹70 Lakhs',
  '₹70 Lakhs – ₹1 Crore',
  'Above ₹1 Crore',
  'Commercial Investment',
];

export const INTEREST_OPTIONS = [
  '2BHK Flat',
  '3BHK Flat',
  'Bungalow / Villa',
  'Commercial Shop',
  'Showroom / Office',
  'Plot / Land',
  'RCC Construction',
  'Material Supply',
  'Just Exploring',
];
